<a href="https://colab.research.google.com/github/vdslab/t-taiki0620/blob/main/joinJson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import json

with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/TextRank2018.json', encoding='utf8')as f:
  TextRank = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/SingleRank2018.json', encoding='utf8')as f:
  SingleRank = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/PositionRank2018.json', encoding='utf8')as f:
  PositionRank = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/TopicRank2018.json', encoding='utf8')as f:
  TopicRank = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/MultipartiteRank2018.json', encoding='utf8')as f:
  MultipartiteRank = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/tfidf2018.json', encoding='utf8')as f:
  tfidf = pd.read_json(f)
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/okapi2018.json', encoding='utf8')as f:
  okapi = pd.read_json(f)

In [2]:
TextRank

      プロジェクトID                                           TextRank
0           16  [{'word': '官邸', 'score': 0.45774238097324305},...
1           15  [{'word': '①', 'score': 0.307690492540347}, {'...
2           52  [{'word': '平和', 'score': 0.571824760182948}, {...
3           35  [{'word': '異業', 'score': 0.171919224528987}, {...
4           84  [{'word': '平和', 'score': 1.156836718550655}, {...
...        ...                                                ...
4368      3574  [{'word': '短期', 'score': 0.533810014604977}, {...
4369        44  [{'word': '等', 'score': 0.49770689186603706}, ...
4370      4895  [{'word': '地域', 'score': 0.456895820736458}, {...
4371      3708  [{'word': '中', 'score': 0.22471945112327102}, ...
4372      4916  [{'word': '輸出', 'score': 0.23415767687122402},...

[4373 rows x 2 columns]

In [3]:
SingleRank

      プロジェクトID                                         SingleRank
0           16  [{'word': '重要', 'score': 0.22719143419183502},...
1           15  [{'word': '①', 'score': 0.232951238893454}, {'...
2           52  [{'word': '平和', 'score': 0.46879636854598405},...
3           35  [{'word': 'デザイン', 'score': 0.07080525371304601...
4           84  [{'word': '平和', 'score': 1.056351079097693}, {...
...        ...                                                ...
4368      3574  [{'word': '気候', 'score': 0.8710442005263821}, ...
4369        44  [{'word': '等', 'score': 0.44924497722440704}, ...
4370      4895  [{'word': '地域', 'score': 0.329369221106517}, {...
4371      3708  [{'word': '人材', 'score': 0.252033314316083}, {...
4372      4916  [{'word': '輸出', 'score': 0.412436952142117}, {...

[4373 rows x 2 columns]

In [4]:
PositionRank

      プロジェクトID                                       PositionRank
0           16  [{'word': '重要', 'score': 0.24954501862401401},...
1           15  [{'word': '政府', 'score': 0.203189022842227}, {...
2           52  [{'word': '協力', 'score': 0.200994108263147}, {...
3           35  [{'word': '伝統', 'score': 0.10769180527144001},...
4           84  [{'word': '国際', 'score': 0.21428239539945002},...
...        ...                                                ...
4368      3574  [{'word': '等', 'score': 0.21432266260511101}, ...
4369        44  [{'word': '等', 'score': 0.6222136736736491}, {...
4370      4895  [{'word': '地域', 'score': 0.201033672002863}, {...
4371      3708  [{'word': '人材', 'score': 0.24687212626356303},...
4372      4916  [{'word': '農林', 'score': 0.23846493108589903},...

[4373 rows x 2 columns]

In [5]:
TopicRank

      プロジェクトID                                          TipicRank
0           16  [{'word': '国内外', 'score': 0.5}, {'word': '重要',...
1           15  [{'word': '成果', 'score': 0.331549597914264}, {...
2           52  [{'word': '国際', 'score': 0.42873627922210505},...
3           35  [{'word': 'マンガ', 'score': 0.075981395906298}, ...
4           84  [{'word': '平和', 'score': 0.578066461354043}, {...
...        ...                                                ...
4354      3574  [{'word': '短期', 'score': 0.13703526921091602},...
4355        44  [{'word': '経済', 'score': 0.18987003114637002},...
4356      4895  [{'word': '農山漁村', 'score': 0.272058935306753},...
4357      3708  [{'word': '小規模', 'score': 0.223283703610612}, ...
4358      4916  [{'word': '農林', 'score': 0.161708194521682}, {...

[4359 rows x 2 columns]

In [12]:
MultipartiteRank

      プロジェクトID                                   MultipartiteRank
0           16  [{'word': '重要', 'score': 0.5}, {'word': '施策', ...
1           15  [{'word': '成果', 'score': 0.331549597914264}, {...
2           52  [{'word': '国際', 'score': 0.42873627922210505},...
3           35  [{'word': 'マンガ', 'score': 0.075981395906298}, ...
4           84  [{'word': '活動', 'score': 0.621845565386278}, {...
...        ...                                                ...
4354      3574  [{'word': '短期', 'score': 0.12218156072326601},...
4355        44  [{'word': '経済', 'score': 0.184906293576029}, {...
4356      4895  [{'word': '農山漁村', 'score': 0.255343926020493},...
4357      3708  [{'word': '小規模', 'score': 0.223283703610612}, ...
4358      4916  [{'word': '農林', 'score': 0.171655107190499}, {...

[4359 rows x 2 columns]

In [7]:
okapi

      プロジェクトID                                              okapi
0           16  [{'word': '首相官邸', 'score': 1.598111024325896},...
1           15  [{'word': '狙い', 'score': 0.882563232093802}, {...
2           52  [{'word': '国際連合平和維持活動等に対する協力に関する法律', 'score': ...
3           35  [{'word': 'マンガ', 'score': 0.941103429864183}, ...
4           84  [{'word': '国際連合平和維持活動', 'score': 1.44439705750...
...        ...                                                ...
4368      3574  [{'word': '汚染物質', 'score': 1.779075575702208},...
4369        44  [{'word': '財政健全化', 'score': 0.7857674184796041...
4370      4895  [{'word': '農山漁村', 'score': 1.124981948211616},...
4371      3708  [{'word': 'サービス業', 'score': 1.196650124326114}...
4372      4916  [{'word': '品目', 'score': 0.6496018020378}, {'w...

[4373 rows x 2 columns]

In [8]:
tfidf

      プロジェクトID                                              tfidf
0           16  [{'word': '首相官邸', 'score': 0.326306106855329},...
1           15  [{'word': '資質', 'score': 0.21499935041885201},...
2           52  [{'word': '国際連合平和維持活動等に対する協力に関する法律', 'score': ...
3           35  [{'word': '魅力', 'score': 0.196144647075349}, {...
4           84  [{'word': '国際連合平和維持活動', 'score': 0.28126529379...
...        ...                                                ...
4368      3574  [{'word': '気候', 'score': 0.40946184950927306},...
4369        44  [{'word': '社会保障', 'score': 0.23658892740700602...
4370      4895  [{'word': '農山漁村', 'score': 0.40472038165406005...
4371      3708  [{'word': '人材', 'score': 0.43538650363746606},...
4372      4916  [{'word': '品目', 'score': 0.214320328733369}, {...

[4373 rows x 2 columns]

In [13]:
obj = []
for i in range(len(MultipartiteRank)):
  obj.append({'プロジェクトID':int(MultipartiteRank.loc[i]['プロジェクトID']),
              'TextRank':TextRank.loc[i]['TextRank'],
              'SingleRank':SingleRank.loc[i]['SingleRank'],
              'PositionRank':PositionRank.loc[i]['PositionRank'],
              'TopicRank':TopicRank.loc[i]['TipicRank'],
              'MultipartiteRank':MultipartiteRank.loc[i]['MultipartiteRank'],
              'tfidf':tfidf.loc[i]['tfidf'],
              'okapi':okapi.loc[i]['okapi']})
  
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/phrase2018.json', 'w', encoding='utf8')as f:
  json.dump(obj, f, indent=2, ensure_ascii=False)

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/pre-judgit/data.json', encoding='utf8')as f:
  df = pd.read_json(f)

In [ ]:
for i in range(len(df)):
  if df.loc[i]['プロジェクトID'] == 52 and df.loc[i]['公開年度'] == 2018:
    print(df.loc[i]['事業名'])
    print(df.loc[i]['事業概要'])

人道救援物資備蓄経費
国際連合等から人道的な国際救援活動への物資協力の要請をうけた場合、迅速に対応できるよう人道救援物資の調達及び備蓄（物資の保管・管理）等の業務を実施している。